Refine and expand yelp categories and additional socket functions
conzensus/conzensus pull request #110
Opened 2023-04-27 22:01 UTC by ssexton1

2023-04-27 22:05 UTC, ssexton1 commented
This pr closes #103, #56, #35, #90 

For issue #56 we will still edit the chooseCandidateActivities function in the room class to make sure it returns non-repeating activities

2023-04-28 23:10 UTC, ssexton1 commented on client/src/index.css
> +}
Adding .logo styling outside the media query seemed to fix the zoomed out issue for now

2023-04-28 23:11 UTC, ssexton1 commented on client/src/socket/socketTesting.js
> +  const forgetToVote = (e) => {
forgetToVote was made to test that the server doesn't  crash when no votes are submitted and the error is caught

2023-04-28 23:13 UTC, ssexton1 commented on server/socket/socket.js
> +        this.chooseNewCandidateActivitiesAndStartVoting(io, room, 20);
Separated out this code into the chooseNewCandidateActivitiesAndStartVoting method for reusability for extra rounds of the game

2023-04-28 23:13 UTC, ssexton1 commented on server/socket/socket.js
> +        }
Catches if all results were vetoed or no results were cast and sends this result to the server

2023-04-28 23:18 UTC, ssexton1 commented on server/socket/socket.js
> +  }
onAnotherRound returns 20 new candidate activites. Currently they are randomized though so it is possible that there are repeating activities which is an issue we will need to fix. This has been created as issue #115

2023-04-30 00:32 UTC, fechan requested changes
Please see comments.

2023-04-30 00:32 UTC, fechan commented on api_documentation.md
> +    "playerList": [] // room player list
What is the data type that will be inside this Array? We should provide some examples of what might appear here.

2023-04-30 00:32 UTC, fechan commented on api_documentation.md
> +    "error": null
We should leave a comment indicating that "error" is not null when success is false, and example of what appears here. Is this a human-readable error message? The name of an exception?

2023-04-30 00:32 UTC, fechan commented on server/data_providers/yelp.js
> +  "notFood": ["active", "arts", "museums", "musicvenues", "shopping", "adultentertainment", "tastingclasses", "artclasses", "localflavor", "photoclasses", "poledancingclasses", "firearmtraining", "sp
I know our target audience is going to be 21+, but should we really include "adultentertainment"? Especially since we want all the broad categories to be checked by default.

I'm sure there's a case for including it, but if we're including this, we should think about the design a bit more to make sure adult entertainment doesn't appear unexpectedly, and make an issue for it.

2023-04-30 01:19 UTC, LisetteRinnen approved these changes
Looks good!

2023-04-30 18:03 UTC, ssexton1 commented on server/data_providers/yelp.js
> +  "notFood": ["active", "arts", "museums", "musicvenues", "shopping", "adultentertainment", "tastingclasses", "artclasses", "localflavor", "photoclasses", "poledancingclasses", "firearmtraining", "sp
I decided to also remove firearmtraining and poledancing classes due to similar issues for now but I made a issue for it so we don't forget in case we want to include them in the future

2023-04-30 20:58 UTC, fechan approved these changes

2023-04-30 21:07 UTC, merged