Lisette/character img
conzensus/conzensus pull request #113
Opened 2023-04-28 08:23 UTC by LisetteRinnen

2023-05-01 08:32 UTC, LisetteRinnen commented
Issue #97

2023-05-01 19:42 UTC, ssexton1 requested changes

2023-05-01 19:42 UTC, ssexton1 commented on client/src/components/functions/addPlayer.js
> +    }
I did some searching and it seems you can access variables using there string name by using something along the lines of 
```
this[var_name]
```
So I think you could clean up the code by doing 

```
this[img]
```
Instead of all the if statements

If it doesn't work no worries but I'd atleast try it to reduce the code in case it works

2023-05-02 16:17 UTC, ssexton1 approved these changes

2023-05-02 19:01 UTC, Shiori520 approved these changes

2023-05-02 20:55 UTC, merged